// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieRates.Data;

namespace MovieRates.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210531201331_Filmes")]
    partial class Filmes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MovieRates.Models.Categorias", b =>
                {
                    b.Property<int>("IdCategorias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategorias");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            IdCategorias = 1,
                            Nome = "Action"
                        },
                        new
                        {
                            IdCategorias = 2,
                            Nome = "Comedy"
                        },
                        new
                        {
                            IdCategorias = 3,
                            Nome = "dasfew"
                        },
                        new
                        {
                            IdCategorias = 4,
                            Nome = "Thriller"
                        },
                        new
                        {
                            IdCategorias = 5,
                            Nome = "Horror"
                        },
                        new
                        {
                            IdCategorias = 6,
                            Nome = "Crime"
                        },
                        new
                        {
                            IdCategorias = 7,
                            Nome = "Drama"
                        },
                        new
                        {
                            IdCategorias = 8,
                            Nome = "Fantasy"
                        },
                        new
                        {
                            IdCategorias = 9,
                            Nome = "Adventure"
                        },
                        new
                        {
                            IdCategorias = 10,
                            Nome = "Sci-Fi"
                        },
                        new
                        {
                            IdCategorias = 11,
                            Nome = "Animation"
                        },
                        new
                        {
                            IdCategorias = 12,
                            Nome = "Mystery"
                        },
                        new
                        {
                            IdCategorias = 13,
                            Nome = "Classic"
                        },
                        new
                        {
                            IdCategorias = 14,
                            Nome = "Romance"
                        },
                        new
                        {
                            IdCategorias = 15,
                            Nome = "Musical"
                        },
                        new
                        {
                            IdCategorias = 16,
                            Nome = "Documentarie"
                        },
                        new
                        {
                            IdCategorias = 17,
                            Nome = "War"
                        },
                        new
                        {
                            IdCategorias = 18,
                            Nome = "Western Films"
                        },
                        new
                        {
                            IdCategorias = 19,
                            Nome = "Romantic Comedy"
                        },
                        new
                        {
                            IdCategorias = 20,
                            Nome = "Foreign Movie"
                        });
                });

            modelBuilder.Entity("MovieRates.Models.FilmeCategorias", b =>
                {
                    b.Property<int>("IdFilmeCategorias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriasFK")
                        .HasColumnType("int");

                    b.Property<int>("FilmesFK")
                        .HasColumnType("int");

                    b.HasKey("IdFilmeCategorias");

                    b.HasIndex("CategoriasFK");

                    b.HasIndex("FilmesFK");

                    b.ToTable("FilmeCategorias");

                    b.HasData(
                        new
                        {
                            IdFilmeCategorias = 1,
                            CategoriasFK = 1,
                            FilmesFK = 1
                        },
                        new
                        {
                            IdFilmeCategorias = 2,
                            CategoriasFK = 2,
                            FilmesFK = 2
                        },
                        new
                        {
                            IdFilmeCategorias = 3,
                            CategoriasFK = 3,
                            FilmesFK = 3
                        },
                        new
                        {
                            IdFilmeCategorias = 4,
                            CategoriasFK = 4,
                            FilmesFK = 4
                        },
                        new
                        {
                            IdFilmeCategorias = 5,
                            CategoriasFK = 5,
                            FilmesFK = 5
                        },
                        new
                        {
                            IdFilmeCategorias = 6,
                            CategoriasFK = 6,
                            FilmesFK = 6
                        },
                        new
                        {
                            IdFilmeCategorias = 7,
                            CategoriasFK = 7,
                            FilmesFK = 7
                        },
                        new
                        {
                            IdFilmeCategorias = 8,
                            CategoriasFK = 8,
                            FilmesFK = 8
                        },
                        new
                        {
                            IdFilmeCategorias = 9,
                            CategoriasFK = 9,
                            FilmesFK = 9
                        },
                        new
                        {
                            IdFilmeCategorias = 10,
                            CategoriasFK = 10,
                            FilmesFK = 10
                        },
                        new
                        {
                            IdFilmeCategorias = 11,
                            CategoriasFK = 11,
                            FilmesFK = 11
                        },
                        new
                        {
                            IdFilmeCategorias = 12,
                            CategoriasFK = 12,
                            FilmesFK = 12
                        },
                        new
                        {
                            IdFilmeCategorias = 13,
                            CategoriasFK = 13,
                            FilmesFK = 13
                        },
                        new
                        {
                            IdFilmeCategorias = 14,
                            CategoriasFK = 14,
                            FilmesFK = 14
                        },
                        new
                        {
                            IdFilmeCategorias = 15,
                            CategoriasFK = 15,
                            FilmesFK = 15
                        },
                        new
                        {
                            IdFilmeCategorias = 16,
                            CategoriasFK = 16,
                            FilmesFK = 16
                        },
                        new
                        {
                            IdFilmeCategorias = 17,
                            CategoriasFK = 17,
                            FilmesFK = 17
                        },
                        new
                        {
                            IdFilmeCategorias = 18,
                            CategoriasFK = 18,
                            FilmesFK = 18
                        },
                        new
                        {
                            IdFilmeCategorias = 19,
                            CategoriasFK = 19,
                            FilmesFK = 19
                        },
                        new
                        {
                            IdFilmeCategorias = 20,
                            CategoriasFK = 20,
                            FilmesFK = 20
                        });
                });

            modelBuilder.Entity("MovieRates.Models.Filmes", b =>
                {
                    b.Property<int>("IdFilmes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Capa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duracao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Elenco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Pontuacao")
                        .HasColumnType("float");

                    b.Property<string>("Realizador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFilmes");

                    b.ToTable("Filmes");

                    b.HasData(
                        new
                        {
                            IdFilmes = 1,
                            Capa = "6Underground.jpg",
                            Data = new DateTime(2019, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Six individuals from all around the globe, each the very best at what they do, have been chosen not only for their skill, but for a unique desire to delete their pasts to change the future.",
                            Duracao = "2h 8min",
                            Elenco = " Ryan Reynolds, Mélanie Laurent, Manuel Garcia-Rulfo ",
                            Link = "https://www.imdb.com/title/tt8106534/?ref_=nv_sr_srsg_0",
                            Pontuacao = 6.0999999999999996,
                            Realizador = "Michael Bay",
                            Titulo = "6 Underground"
                        },
                        new
                        {
                            IdFilmes = 2,
                            Capa = "SpenserConfidential.jpg",
                            Data = new DateTime(2020, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "When two Boston police officers are murdered, ex-cop Spenser teams up with his no-nonsense roommate, Hawk, to take down criminals.",
                            Duracao = "1h 51min",
                            Elenco = "Mark Wahlberg, Winston Duke, Alan Arkin",
                            Link = "https://www.imdb.com/title/tt8629748/?ref_=nv_sr_srsg_0",
                            Pontuacao = 6.2000000000000002,
                            Realizador = "Peter Berg",
                            Titulo = "Spenser Confidential"
                        },
                        new
                        {
                            IdFilmes = 3,
                            Capa = "Extraction.jpg",
                            Data = new DateTime(2020, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Tyler Rake, a fearless black market mercenary, embarks on the most deadly extraction of his career when he's enlisted to rescue the kidnapped son of an imprisoned international crime lord.",
                            Duracao = "1h 56min",
                            Elenco = "Chris Hemsworth, Bryon Lerum, Ryder Lerum",
                            Link = "https://www.imdb.com/title/tt8936646/?ref_=nv_sr_srsg_0",
                            Pontuacao = 6.7000000000000002,
                            Realizador = "Sam Hargrave",
                            Titulo = "Extraction"
                        },
                        new
                        {
                            IdFilmes = 4,
                            Capa = "LoveAndMonsters.jpg",
                            Data = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Seven years after he survived the monster apocalypse, lovably hapless Joel leaves his cozy underground bunker behind on a quest to reunite with his ex.",
                            Duracao = "1h 49min",
                            Elenco = "Dylan O'Brien, Jessica Henwick, Michael Rooker",
                            Link = "https://www.imdb.com/title/tt2222042/?ref_=nv_sr_srsg_0",
                            Pontuacao = 7.0,
                            Realizador = "Michael Matthews",
                            Titulo = "Love and Monsters"
                        },
                        new
                        {
                            IdFilmes = 5,
                            Capa = "Skyscraper.jpg",
                            Data = new DateTime(2018, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "A security expert must infiltrate a burning skyscraper, 225 stories above ground, when his family is trapped inside by criminals.",
                            Duracao = "1h 42min",
                            Elenco = "Dwayne Johnson, Neve Campbell, Chin Han",
                            Link = "https://www.imdb.com/title/tt5758778/?ref_=nv_sr_srsg_0",
                            Pontuacao = 5.7999999999999998,
                            Realizador = "Rawson Marshall Thurber",
                            Titulo = "Skyscraper"
                        },
                        new
                        {
                            IdFilmes = 6,
                            Capa = "Fighting.jpg",
                            Data = new DateTime(2009, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "In New York City, a young counterfeiter is introduced to the world of underground street fighting by a seasoned scam artist, who becomes his manager on the bare-knuckling brawling circuit.",
                            Duracao = "1h 45min",
                            Elenco = "Channing Tatum, Terrence Howard, Luis Guzmán",
                            Link = "https://www.imdb.com/title/tt1082601/?ref_=nv_sr_srsg_0",
                            Pontuacao = 5.5999999999999996,
                            Realizador = "Dito Montiel",
                            Titulo = "Fighting"
                        },
                        new
                        {
                            IdFilmes = 7,
                            Capa = "Avatar.jpg",
                            Data = new DateTime(2009, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
                            Duracao = "2h 42min",
                            Elenco = "Sam Worthington, Zoe Saldana, Sigourney Weaver",
                            Link = "https://www.imdb.com/title/tt0499549/?ref_=nv_sr_srsg_3",
                            Pontuacao = 7.7999999999999998,
                            Realizador = "James Cameron",
                            Titulo = "Avatar"
                        },
                        new
                        {
                            IdFilmes = 8,
                            Capa = "Faster.jpg",
                            Data = new DateTime(2010, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "An ex-con gets on a series of apparently unrelated killings. He gets tracked by a veteran cop with secrets of his own and an egocentric hit man.",
                            Duracao = "1h 38min",
                            Elenco = " Dwayne Johnson, Billy Bob Thornton, Maggie Grace",
                            Link = "https://www.imdb.com/title/tt1433108/?ref_=nv_sr_srsg_0",
                            Pontuacao = 6.4000000000000004,
                            Realizador = "George Tillman Jr.",
                            Titulo = "Faster"
                        },
                        new
                        {
                            IdFilmes = 9,
                            Capa = "Hancock.jpg",
                            Data = new DateTime(2008, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Hancock is a superhero whose ill-considered behavior regularly causes damage in the millions. He changes when the person he saves helps him improve his public image.",
                            Duracao = "1h 32min",
                            Elenco = "Will Smith, Charlize Theron, Jason Bateman",
                            Link = "https://www.imdb.com/title/tt0448157/?ref_=nv_sr_srsg_0",
                            Pontuacao = 6.4000000000000004,
                            Realizador = " Peter Berg",
                            Titulo = "Hancock"
                        },
                        new
                        {
                            IdFilmes = 10,
                            Capa = "DeathRace.jpg",
                            Data = new DateTime(2008, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Ex-con Jensen Ames is forced by the warden of a notorious prison to compete in our post-industrial world's most popular sport: a car race in which inmates must brutalize and kill one another on the road to victory.",
                            Duracao = "1h 45min",
                            Elenco = " Jason Statham, Joan Allen, Tyrese Gibson",
                            Link = "https://www.imdb.com/title/tt0452608/?ref_=nv_sr_srsg_0",
                            Pontuacao = 6.4000000000000004,
                            Realizador = "Paul W.S. Anderson",
                            Titulo = "Death Race"
                        },
                        new
                        {
                            IdFilmes = 11,
                            Capa = "DeathRace2.jpg",
                            Data = new DateTime(2011, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Explores the origins of the first 'Frankenstein' car driver, Carl 'Luke' Lucas, who died in a race at the beginning of the first film.",
                            Duracao = "1h 36min",
                            Elenco = " Luke Goss, Lauren Cohan, Sean Bean",
                            Link = "https://www.imdb.com/title/tt1500491/?ref_=nv_sr_srsg_5",
                            Pontuacao = 5.5999999999999996,
                            Realizador = "Roel Reiné",
                            Titulo = "Death Race 2"
                        },
                        new
                        {
                            IdFilmes = 12,
                            Capa = "DeathRace3.jpg",
                            Data = new DateTime(2013, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Convicted cop-killer Carl Lucas, aka Frankenstein, is a superstar driver in the brutal prison yard demolition derby known as Death Race. Only one victory away from winning freedom for himself and his pit crew.",
                            Duracao = "1h 44min",
                            Elenco = " Luke Goss, Tanit Phoenix Copley, Danny Trejo",
                            Link = "https://www.imdb.com/title/tt1988591/?ref_=nv_sr_srsg_6",
                            Pontuacao = 5.5,
                            Realizador = "Roel Reiné",
                            Titulo = "Death Race: Inferno"
                        },
                        new
                        {
                            IdFilmes = 13,
                            Capa = "DeathRace4.jpg",
                            Data = new DateTime(2018, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "With the U.S. on its knees, suffering from complete societal collapse and rampant anarchy, the nefarious Weyland Corporation has created a vast and impenetrable prison-city called 'The Sprawl', where more than 400,000 inmates are left to rot. Under those circumstances, the secluded community's undisputed ruler is the unknown iconic driver known only as 'Frankenstein', who is still the king of the deadly Death Races, now broadcast over the Dark Web. Then, a new powerful contestant arrives--the mysterious, Connor Gibson--who is hell-bent on beating Frankenstein himself at his own game; however, this is easier said than done. Does Connor have what it takes to humiliate the master of the races before millions of spectators?",
                            Duracao = "1h 51min",
                            Elenco = " Lucy Aarden, Nicholas Aaron, Jasette Amos",
                            Link = "https://www.imdb.com/title/tt3807900/?ref_=nv_sr_srsg_3",
                            Pontuacao = 5.2000000000000002,
                            Realizador = "Don Michael Paul",
                            Titulo = "Death Race 4: Beyond Anarchy"
                        },
                        new
                        {
                            IdFilmes = 14,
                            Capa = "EdgeOfTomorrow.jpg",
                            Data = new DateTime(2014, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "A soldier fighting aliens gets to relive the same day over and over again, the day restarting every time he dies.",
                            Duracao = "1h 53min",
                            Elenco = " Tom Cruise, Emily Blunt, Bill Paxton",
                            Link = "https://www.imdb.com/title/tt1631867/?ref_=nv_sr_srsg_0",
                            Pontuacao = 7.9000000000000004,
                            Realizador = " Doug Liman",
                            Titulo = "Edge of Tomorrow"
                        },
                        new
                        {
                            IdFilmes = 15,
                            Capa = "Avengement.jpg",
                            Data = new DateTime(2019, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "After years of assaults on him in prison, convicted felon Cain Burgess escapes for avengement on those responsible.",
                            Duracao = " 1h 27min",
                            Elenco = " Scott Adkins, Craig Fairbrass, Thomas Turgoose",
                            Link = "https://www.imdb.com/title/tt8836988/?ref_=nv_sr_srsg_0",
                            Pontuacao = 6.5,
                            Realizador = " Jesse V. Johnson",
                            Titulo = "Avengement"
                        },
                        new
                        {
                            IdFilmes = 16,
                            Capa = "Saw.jpg",
                            Data = new DateTime(2005, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Two strangers awaken in a room with no recollection of how they got there, and soon discover they're pawns in a deadly game perpetrated by a notorious serial killer.",
                            Duracao = "1h 43min",
                            Elenco = "Cary Elwes, Leigh Whannell, Danny Glover",
                            Link = "https://www.imdb.com/title/tt0387564/?ref_=fn_al_tt_1",
                            Pontuacao = 7.5999999999999996,
                            Realizador = "James Wan",
                            Titulo = "Saw - Enigma Mortal"
                        },
                        new
                        {
                            IdFilmes = 17,
                            Capa = "SawV.jpg",
                            Data = new DateTime(2017, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Bodies are turning up around the city, each having met a uniquely gruesome demise. As the investigation proceeds, evidence points to one suspect: John Kramer, the man known as Jigsaw, who has been dead for over 10 years.",
                            Duracao = "1h 32min",
                            Elenco = "Matt Passmore, Tobin Bell, Callum Keith Rennie",
                            Link = "https://www.imdb.com/title/tt3348730/?ref_=tt_mv_close",
                            Pontuacao = 5.7999999999999998,
                            Realizador = "Michael Spierig, Peter Spierig",
                            Titulo = "Jigsaw: O Legado de Saw"
                        },
                        new
                        {
                            IdFilmes = 18,
                            Capa = "SawII.jpg",
                            Data = new DateTime(2016, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "A detective and his team must rescue 8 people trapped in a factory by the twisted serial killer known as Jigsaw.",
                            Duracao = "1h 33min",
                            Elenco = "Donnie Wahlberg, Beverley Mitchell, Franky G",
                            Link = "https://www.imdb.com/title/tt0432348/?ref_=tt_mv_close",
                            Pontuacao = 6.5999999999999996,
                            Realizador = "Darren Lynn Bousman",
                            Titulo = "Saw II - A Experiência do Medo"
                        },
                        new
                        {
                            IdFilmes = 19,
                            Capa = "SawIII.jpg",
                            Data = new DateTime(2018, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "As a deadly battle rages over Jigsaw's brutal legacy, a group of Jigsaw survivors gathers to seek the support of self-help guru and fellow survivor Bobby Dagen, a man whose own dark secrets unleash a new wave of terror.",
                            Duracao = "1h 30min",
                            Elenco = "Tobin Bell, Costas Mandylor, Betsy Russell",
                            Link = "https://www.imdb.com/title/tt1477076/?ref_=tt_mv_close",
                            Pontuacao = 5.5999999999999996,
                            Realizador = "Kevin Greutert",
                            Titulo = "Saw 3D - O Capítulo Final"
                        },
                        new
                        {
                            IdFilmes = 20,
                            Capa = "EscapeRoom.jpg",
                            Data = new DateTime(2017, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Six friends test their intelligence when an escape room they participate in takes a dark and twisted turn.",
                            Duracao = "1h 21min",
                            Elenco = "Evan Williams, Annabelle Stephenson, Elisabeth Hower",
                            Link = "https://www.imdb.com/title/tt5159414/?ref_=tt_mv_close",
                            Pontuacao = 4.2000000000000002,
                            Realizador = "Will Wernick",
                            Titulo = "Escape Room"
                        },
                        new
                        {
                            IdFilmes = 21,
                            Capa = "EscapeRoomII.jpg",
                            Data = new DateTime(2019, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Six strangers find themselves in a maze of deadly mystery rooms and must use their wits to survive.",
                            Duracao = " 1h 39min",
                            Elenco = "Taylor Russell, Logan Miller, Jay Ellis",
                            Link = "https://www.imdb.com/title/tt5886046/?ref_=tt_mv_close",
                            Pontuacao = 6.4000000000000004,
                            Realizador = "Adam Robitel",
                            Titulo = "Escape Room 2"
                        },
                        new
                        {
                            IdFilmes = 22,
                            Capa = "IT.jpg",
                            Data = new DateTime(2017, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster, which disguises itself as a clown and preys on the children of Derry, their small Maine town.",
                            Duracao = "2h 15min",
                            Elenco = "Bill Skarsgård, Jaeden Martell, Finn Wolfhard",
                            Link = "https://www.imdb.com/title/tt1396484/?ref_=tt_mv_close",
                            Pontuacao = 7.2999999999999998,
                            Realizador = "Andy Muschietti",
                            Titulo = "It"
                        },
                        new
                        {
                            IdFilmes = 23,
                            Capa = "ITII.jpg",
                            Data = new DateTime(2019, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Twenty-seven years after their first encounter with the terrifying Pennywise, the Losers Club have grown up and moved away, until a devastating phone call brings them back.",
                            Duracao = "2h 49min",
                            Elenco = "Jessica Chastain, James McAvoy, Bill Hader",
                            Link = "https://www.imdb.com/title/tt7349950/?ref_=tt_mv_close",
                            Pontuacao = 6.5,
                            Realizador = "Andy Muschietti",
                            Titulo = "It Capítulo 2"
                        });
                });

            modelBuilder.Entity("MovieRates.Models.Reviews", b =>
                {
                    b.Property<int>("IdReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilmesFK")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("int");

                    b.Property<int>("UtilizadoresFK")
                        .HasColumnType("int");

                    b.HasKey("IdReview");

                    b.HasIndex("FilmesFK");

                    b.HasIndex("UtilizadoresFK");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MovieRates.Models.Utilizadores", b =>
                {
                    b.Property<int>("IdUtilizador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUtilizador");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieRates.Models.FilmeCategorias", b =>
                {
                    b.HasOne("MovieRates.Models.Categorias", "Categoria")
                        .WithMany("ListaDeCategorias")
                        .HasForeignKey("CategoriasFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieRates.Models.Filmes", "Filme")
                        .WithMany("ListaDeCategorias")
                        .HasForeignKey("FilmesFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Filme");
                });

            modelBuilder.Entity("MovieRates.Models.Reviews", b =>
                {
                    b.HasOne("MovieRates.Models.Filmes", "Filme")
                        .WithMany("ListaDeFilmes")
                        .HasForeignKey("FilmesFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieRates.Models.Utilizadores", "Utilizador")
                        .WithMany("ListaDeReviews")
                        .HasForeignKey("UtilizadoresFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filme");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("MovieRates.Models.Categorias", b =>
                {
                    b.Navigation("ListaDeCategorias");
                });

            modelBuilder.Entity("MovieRates.Models.Filmes", b =>
                {
                    b.Navigation("ListaDeCategorias");

                    b.Navigation("ListaDeFilmes");
                });

            modelBuilder.Entity("MovieRates.Models.Utilizadores", b =>
                {
                    b.Navigation("ListaDeReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
